"""update profile models with title, current, technologies, level fields

Revision ID: 10d7e7e0ea63
Revises: 8b14bc1365ae
Create Date: 2026-01-30 04:16:59.741995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d7e7e0ea63'
down_revision = '8b14bc1365ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('experiences', sa.Column('current', sa.String(), nullable=True))
    op.add_column('experiences', sa.Column('technologies', sa.Text(), nullable=True))
    op.drop_column('experiences', 'position')
    op.add_column('skills', sa.Column('level', sa.String(length=50), nullable=True))
    op.drop_column('skills', 'proficiency_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('proficiency_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('skills', 'level')
    op.add_column('experiences', sa.Column('position', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('experiences', 'technologies')
    op.drop_column('experiences', 'current')
    op.drop_column('experiences', 'title')
    # ### end Alembic commands ###
