"""update_generated_documents_fields

Revision ID: 9f3e15511125
Revises: 5d8e9f1a2b3c
Create Date: 2026-01-30 11:42:45.767143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f3e15511125'
down_revision = '5d8e9f1a2b3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_documents', sa.Column('pdf_path', sa.String(length=500), nullable=True))
    op.add_column('generated_documents', sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('generated_documents', sa.Column('filename', sa.String(length=255), nullable=True))
    op.add_column('generated_documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('generated_documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('generated_documents', 'pdf_url')
    op.drop_index('job_offer_embedding_idx', table_name='job_offers', postgresql_using='hnsw')
    op.drop_index('profile_embedding_idx', table_name='profiles', postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('profile_embedding_idx', 'profiles', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index('job_offer_embedding_idx', 'job_offers', ['embedding'], unique=False, postgresql_using='hnsw')
    op.add_column('generated_documents', sa.Column('pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('generated_documents', 'updated_at')
    op.drop_column('generated_documents', 'file_size')
    op.drop_column('generated_documents', 'filename')
    op.drop_column('generated_documents', 'generation_params')
    op.drop_column('generated_documents', 'pdf_path')
    # ### end Alembic commands ###
